[workspace]
resolver = "2"
members = ["crates/cube", "crates/cube_rand", "crates/maze"]

[workspace.package]
version = "1.1.0"
edition = "2024"
# rust-version = "1.88"
license = "MIT"
repository = "https://github.com/LittleGuest/xiaofang"
authors = ["LittleGuest <2190975784@qq.com>"]

[workspace.dependencies]
esp-hal = { version = "~1.1.0", features = ["defmt", "esp32c3", "unstable"] }

esp-rtos = { version = "0.3.0", features = [
  "defmt",
  "embassy",
  "esp-alloc",
  "esp-radio",
  "esp32c3",
] }

defmt = "1.0.1"
esp-bootloader-esp-idf = { version = "0.5.0", features = ["defmt", "esp32c3"] }

embassy-net = { version = "0.9.1", features = [
  "defmt",
  "dhcpv4",
  "medium-ethernet",
  "tcp",
  "udp",
] }
embedded-io = { version = "0.7.1", features = ["defmt"] }
embedded-io-async = { version = "0.7.0", features = ["defmt"] }
esp-alloc = { version = "0.10.0", features = ["defmt"] }
esp-backtrace = { version = "0.19.0", features = [
  "defmt",
  "esp32c3",
  "panic-handler",
] }
esp-println = { version = "0.17.0", features = ["defmt-espflash", "esp32c3"] }
# for more networking protocol support see https://crates.io/crates/edge-net
bleps = { git = "https://github.com/bjoernQ/bleps", package = "bleps", rev = "a5148d8ae679e021b78f53fd33afb8bb35d0b62e", features = [
  "async",
  "macros",
] }
embassy-executor = { version = "0.10.0", features = ["defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt"] }
esp-radio = { version = "0.18.0", features = [
  "ble",
  "coex",
  "defmt",
  "esp-alloc",
  "esp32c3",
  "unstable",
  "wifi",
  "esp-now",
] }
smoltcp = { version = "0.13.0", default-features = false, features = [
  "defmt",
  "medium-ethernet",
  "multicast",
  "proto-dhcpv4",
  "proto-dns",
  "proto-ipv4",
  "socket-dns",
  "socket-icmp",
  "socket-raw",
  "socket-tcp",
  "socket-udp",
] }

critical-section = "1.2.0"
static_cell = "2.1.1"
heapless = { version = "0.9.3", default-features = false }
embassy-sync = "0.8.0"
mpu6050-dmp = "0.6.0"
embedded-hal = "1.0.0"
embedded-graphics = "0.8.1"
embedded-graphics-core = "0.4.0"
esp-storage = { version = "0.9.0", features = ["defmt", "esp32c3"] }
embedded-storage = "0.3.1"
smart-leds-matrix = "0.2.0"
smart-leds = "0.4.0"
microfft = { version = "0.6.0", default-features = false, features = [
  "size-64",
] }
micromath = "2.1.0"
spectrum-analyzer = "1.5.0"
ws2812-spi = "0.5.0"
cube_rand = { path = "../cube_rand/" }
maze = { path = "../maze" }
embassy-futures = "0.1.1"
rand_core = "0.9.3"
rand = { version = "0.9.2", default-features = false }
