[package]
name = "cube"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
esp-hal.workspace = true
esp-rtos.workspace = true
defmt.workspace = true
esp-bootloader-esp-idf.workspace = true
bleps.workspace = true
critical-section.workspace = true
embedded-io.workspace = true
esp-alloc.workspace = true
esp-println.workspace = true
esp-radio.workspace = true
smoltcp.workspace = true
embedded-io-async.workspace = true
embassy-executor.workspace = true
embassy-time.workspace = true
static_cell.workspace = true
heapless.workspace = true
embassy-sync.workspace = true
mpu6050-dmp.workspace = true
embedded-hal.workspace = true
embedded-graphics.workspace = true
embedded-graphics-core.workspace = true
esp-storage.workspace = true
embedded-storage.workspace = true
smart-leds-matrix.workspace = true
smart-leds.workspace = true
microfft.workspace = true
spectrum-analyzer.workspace = true
ws2812-spi.workspace = true
cube_rand = { path = "../cube_rand/" }
maze = { path = "../maze" }
embassy-futures.workspace = true

# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2         # prefer slower builds but better debugging experience
lto = 'fat'
opt-level = 's'
