[package]
name = "cube"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
esp-hal.workspace = true
esp-rtos.workspace = true
defmt.workspace = true
esp-bootloader-esp-idf.workspace = true
critical-section.workspace = true
embedded-io.workspace = true
esp-alloc.workspace = true
esp-println.workspace = true
esp-radio.workspace = true
embedded-io-async.workspace = true
embassy-executor.workspace = true
embassy-time.workspace = true
static_cell.workspace = true
heapless.workspace = true
embassy-sync.workspace = true
mpu6050-dmp.workspace = true
embedded-hal.workspace = true
embedded-graphics.workspace = true
embedded-graphics-core.workspace = true
esp-storage.workspace = true
embedded-storage.workspace = true
smart-leds-matrix.workspace = true
smart-leds.workspace = true
microfft.workspace = true
micromath.workspace = true
cube_rand.workspace = true
maze.workspace = true
embassy-futures.workspace = true
nb.workspace = true
esp-hal-smartled2.workspace = true
